#!/usr/bin/env sh

#
# AUTHOR:      Michael Espena <michael.esp42@pm.me>
# DATE:        Tue Oct 11 08:08:22 PM PST 2022
# DESCRIPTION: Script for the time module in polybar
#

#
# The final output of this script is the result of the date command in the last
# line of this file and that is all the time module for polybar really needs.
# In my polybar set up I'm using the builtin battery module. Upon reading
# polybar's documentation it does not seem that I can use the battery module to
# send notifications when the battery level is already full or low. Since this
# script does not do much anyway I going to use this to check the battery level
# and send battery level related notifications. In this way I don't have to add
# another `custom/script` module just for that purpose.
#

BATTERY_LOW_LEVEL=20
BATTERY_FULL_FILE=/tmp/batter_full_file

battery_level=$(cat /sys/class/power_supply/BAT0/capacity)
battery_status=$(cat /sys/class/power_supply/BAT0/status)

if [ "$battery_level" -lt "$BATTERY_LOW_LEVEL" ] &&
  [ "$battery_status" = "Discharging" ]; then

  notify-send --urgency=critical "Battery low" "Please, charge immediately."
  rm -f "$BATTERY_FULL_FILE"

elif [ "$battery_status" = "Full" ] && [ ! -f "$BATTERY_FULL_FILE" ]; then

  notify-send "Battery full" "You may now unplug the charger."
  touch "$BATTERY_FULL_FILE"

fi

date +%H:%M
