#!/usr/bin/env sh

#
# AUTHOR:      Michael Espena <michael.esp42@pm.me>
# DATE:        Sun Oct 16 04:40:12 PM PST 2022
# DESCRIPTION: Script for use in a scratchpad to launch `qalc` cli calculator.
#

# 
# DEPENDENCIES:
#   - qalc
#   - figlet
#   - lolcrab (https://github.com/mazznoer/lolcrab)

# Totally unnecessary part just added for some bling
# prints ascii `QALC` and additional descriptive text with some colors
figlet "QALC" | lolcrab
echo "--------------------------" | lolcrab
printf "%s\n%s\n" " Powerful and easy to use" " command line calculator" |
  lolcrab
echo "--------------------------" | lolcrab

qalc
