#!/usr/bin/env sh

#
# AUTHOR:      Michael Espena <michael.esp42@pm.me>
# DATE:        Thu Oct 13 09:15:05 AM PST 2022
# DESCRIPTION: Script to quickly install a VM
#

#
# DEPENDENCIES:
#   - qemu-system_x86_64
#

if [ "$#" -ne 2 ]; then
  echo "Usage: qemu-create-img <install-iso> <image-name>" >&2
  exit 1
fi

qemu-system-x86_64 -enable-kvm -boot menu=on -cdrom "$1" -drive file="$2" \
  -m 3G -cpu host -smp 2 -vga virtio -display sdl,gl=on
