#!/usr/bin/env sh

#
# AUTHOR:      Michael Espena <michael.esp42@pm.me>
# DATE:        Thu Oct 13 09:15:05 AM PST 2022
# DESCRIPTION: Script to quickly run a VM
#

#
# DEPENDENCIES:
#   - qemu-system_x86_64
#

qemu-system-x86_64 -enable-kvm -boot menu=on -drive file="$1" -m 3G -cpu host \
  -smp 2 -vga virtio -display sdl,gl=on
